apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: movie-ratings-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ShashikiranVirupakshappa/movie-ratings.git
    targetRevision: HEAD
    path: dev-k8s-manifest-files
  destination:
    server: https://kubernetes.default.svc
    namespace: moviedb

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
