apiVersion: v1
kind: Service
metadata:
  name: movie-ratings-service
  namespace: default
  labels:
    app: movie-ratings-service
spec:
  ports:
    -
      port: 8083
      targetPort: 8083
      protocol: TCP
      nodePort: 30001
  selector:
    app: movie-ratings
  type: NodePort